version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "almas-awsomepets"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ld6pkhhe0xdt"
s3_prefix = "almas-awsomepets"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"v1\""
confirm_changeset = true
